### ISSUE TITLE
Can't open PIM

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#387]
Opening a PIM results in the client showing the Load Error dialog. On the server, the error seems to point to a permissions issue.

[01/Apr/2015:19:25:16]  Opening file /var/lib/slycat/data-store/2a/e0/8b/2ae08b98b30048f884a912dbf4f13649.hdf5
[01/Apr/2015:19:25:16] HTTP
Request Headers:
  AUTHORIZATION: Basic c2x5Y2F0OnNseWNhdA==
  COOKIE: slycatauth=c5ee7b395007402681aef5626e36d3d9
  X-FORWARDED-PROTO: https
  HOST: 192.168.59.103
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:36.0) Gecko/20100101 Firefox/36.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  X-FORWARDED-FOR: 192.168.59.3
  Content-Type: application/json
  REFERER: https://192.168.59.103/models/78f6272443f24c4fb83fd1d6b59f7013?bid=3e8cb5cafeb835078a7b74f886c2100b
  ACCEPT-ENCODING: gzip, deflate
[01/Apr/2015:19:25:16] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 60, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/slycat/src/slycat/packages/slycat/web/server/handlers.py", line 987, in get_model_table_metadata
    with slycat.web.server.hdf5.open(artifact, "r+") as file: # We have to open the file with writing enabled because the statistics cache may need to be updated.
  File "/home/slycat/src/slycat/packages/slycat/web/server/hdf5.py", line 30, in open
    return h5py.File(array_path, mode=mode)
  File "/usr/lib64/python2.7/site-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/usr/lib64/python2.7/site-packages/h5py/_hl/files.py", line 81, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:1724)
IOError: unable to open file (File accessibilty: Unable to open file)

**Comment by tshead2** [comment]
Due to changes in configuration, the server was looking for data in a different data-store directory than the one used to create the model.  This can happen during development when the data-store is configured differently for production than development.  The fix is to keep the two in sync.
