### ISSUE TITLE
Travis failing with new file api upload change 

### ISSUE THREAD

**Issue by Mletter1** [sandialabs/slycat#513]
```bash
127.0.0.1 - slycat [14/Oct/2015:16:36:24] "POST /projects/2a0bdd5861273637aa6fe4731c229397/models HTTP/1.1" 201 42 "https://localhost/projects/2a0bdd5861273637aa6fe4731c229397" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0"
[14/Oct/2015:16:36:25]  Starting upload session cleanup worker.
[14/Oct/2015:16:36:25]  Upload session cleanup worker running.
[14/Oct/2015:16:36:25]  Creating upload session for 127.0.0.1
127.0.0.1 - slycat [14/Oct/2015:16:36:25] "POST /uploads HTTP/1.1" 201 42 "https://localhost/projects/2a0bdd5861273637aa6fe4731c229397" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0"
Exception in thread Upload Monitor:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/slycat/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/travis/miniconda/envs/slycat/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/travis/build/sandialabs/slycat/packages/slycat/web/server/upload.py", line 281, in _session_monitor
    for storage in glob.glob(os.path.join(root(), "*")):
  File "/home/travis/build/sandialabs/slycat/packages/slycat/web/server/upload.py", line 50, in root
    root.path = cherrypy.tree.apps[""].config["slycat-web-server"]["upload-store"]
KeyError: 'upload-store'
[14/Oct/2015:16:36:25] HTTP Traceback (most recent call last):
  File "/home/travis/miniconda/envs/slycat/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/travis/miniconda/envs/slycat/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/travis/miniconda/envs/slycat/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/travis/build/sandialabs/slycat/packages/slycat/web/server/handlers.py", line 617, in put_upload_file_part
    with slycat.web.server.upload.get_session(uid) as session:
  File "/home/travis/build/sandialabs/slycat/packages/slycat/web/server/upload.py", line 232, in get_session
    _expire_session(uid)
  File "/home/travis/build/sandialabs/slycat/packages/slycat/web/server/upload.py", line 272, in _expire_session
    if now - session.accessed > slycat.web.server.config["slycat-web-server"]["upload-session-timeout"]:
KeyError: 'upload-session-timeout'
[14/Oct/2015:16:36:25] HTTP 
Request Headers:
  AUTHORIZATION: Basic c2x5Y2F0OnNseWNhdA==
  COOKIE: slycatauth=0c3d325257fe409ca515eccc6f94397a
  Remote-Addr: 127.0.0.1
  Content-Length: 302
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0
  REFERER: https://localhost/projects/2a0bdd5861273637aa6fe4731c229397
  X-REQUESTED-WITH: XMLHttpRequest
  X-FORWARDED-PROTO: https
  HOST: localhost
  ACCEPT: */*
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  X-FORWARDED-FOR: 127.0.0.1
  Content-Type: multipart/form-data; boundary=---------------------------10542211927877692281585889892
  ACCEPT-ENCODING: gzip, deflate
127.0.0.1 - slycat [14/Oct/2015:16:36:25] "PUT /uploads/73c162f20a11402baf5b776b5b44a90b/files/0/parts/0 HTTP/1.1" 500 1904 "https://localhost/projects/2a0bdd5861273637aa6fe4731c229397" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0"
127.0.0.1 - slycat [14/Oct/2015:16:36:25] "GET /templates/slycat-alert.html HTTP/1.1" 200 1039 "https://localhost/projects/2a0bdd5861273637aa6fe4731c229397" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0"
[14/Oct/2015:16:36:25]  Caching 1 projects, 1 models, sequence 985.
And I select a local file                          # features/steps/slycat-project.py:41 11.126s
      Traceback (most recent call last):
        File "/home/travis/miniconda/envs/slycat/lib/python2.7/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/home/travis/miniconda/envs/slycat/lib/python2.7/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "features/steps/slycat-project.py", line 47, in step_impl
          context.browser.wait_until_visible((By.XPATH, "//slycat-table-ingestion/div"))
        File "features/steps/slycat-web-server.py", line 43, in wait_until_visible
          self.wait.until(EC.visibility_of_element_located(element_tuple))
        File "/home/travis/miniconda/envs/slycat/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
          raise TimeoutException(message, screen, stacktrace)
      TimeoutException: Message: 
      
      
      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): localhost
    And I select values for the columns                # None
    Then I should be on the model page                 # None
```

**Comment by Mletter1** [comment]
Cause by feature addition from  #493

**Comment by Mletter1** [comment]
The config.ini file was out of date
