### ISSUE TITLE
import slycat.darray broken

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#516]
```python
import slycat.darray
```
results in an error:
```python
>>> import slycat.darray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slycat/src/slycat/packages/slycat/darray.py", line 31, in <module>
    import slycat.email
  File "/home/slycat/src/slycat/packages/slycat/email.py", line 2, in <module>
    import slycat.web.server
  File "/home/slycat/src/slycat/packages/slycat/web/server/__init__.py", line 11, in <module>
    import slycat.hdf5
  File "/home/slycat/src/slycat/packages/slycat/hdf5.py", line 8, in <module>
    class DArray(slycat.darray.Prototype):
AttributeError: 'module' object has no attribute 'darray'
```
The problem might be with the fact that slycat.darray imports slycat.email, which imports slycat.web.server, which imports slycat.hdf5, which tries to import slycat.darray, which is in the process of being imported?

**Comment by srbdev** [comment]
Modifying the scope of the import works because the function send_error is parsed but not executed. When it is finally called, all modules have been imported so Python can resolve the import statement inside the function.
