### ISSUE TITLE
slycat-create-timeseries-model-from-hdf5.py no longer works

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#536]
When trying to run the slycat-create-timeseries-model-from-hdf5.py script with the --no-verify option, I get the following error:
```
$ ./slycat-create-timeseries-model-from-hdf5.py --no-verify sample-timeseries
slycat password: 
Traceback (most recent call last):
  File "./slycat-create-timeseries-model-from-hdf5.py", line 69, in <module>
    pid = connection.find_or_create_project(arguments.project_name, arguments.project_description)
  File "/home/slycat/src/slycat/packages/slycat/web/client/__init__.py", line 795, in find_or_create_project
    projects = [project for project in self.get_projects()["projects"] if project["name"] == name]
  File "/home/slycat/src/slycat/packages/slycat/web/client/__init__.py", line 457, in get_projects
    return self.request("GET", "/projects", headers={"accept":"application/json"})
  File "/home/slycat/src/slycat/packages/slycat/web/client/__init__.py", line 117, in request
    response = self.session.request(method, uri, verify=self.ssl_verify, **keywords)
TypeError: request() got multiple values for keyword argument 'verify'
```
I suspect it has something to do with commit 50b3fab98acc067c5ece9dda107a84a4581f123e

**Comment by Mletter1** [comment]
That's really weird since verify is an argument that gets passed to the request api and is automatically supposed to be set to true.
