### ISSUE TITLE
Push scripts no longer work due to authentication problem

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#714]
Push scripts no longer accept the slycat user password. Here's the error I get:

```
slycat password: 
/home/slycat/install/conda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "dac-create-model.py", line 349, in <module>
    connection = slycat.web.client.connect(arguments)
  File "/home/slycat/src/slycat/packages/slycat/web/client/__init__.py", line 869, in connect
    return Connection(auth=(arguments.user, arguments.password if arguments.password is not None else getpass.getpass("%s password: " % arguments.user)), host=arguments.host, proxies={"http":arguments.http_proxy, "https":arguments.https_proxy}, **keywords)
  File "/home/slycat/src/slycat/packages/slycat/web/client/__init__.py", line 112, in __init__
    raise NameError('bad username or password, for username:%s' % keywords.get("auth", ("", ""))[0])
NameError: bad username or password, for username:slycat
```

**Comment by Mletter1** [comment]
completed with 24de391
